# Generated by Django 4.0.3 on 2022-04-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
